/** 1.5D profil modeli varsayılan ayarları (UI sihirbazı da kullanır — modelin tamamını içe aktarmadan) */
import { ProfileSettings } from '../types';
import { KBM_COEFFICIENT, PB_DENSITY_EXPONENT, PB_GRADIENT } from './pedestal/eped1';

export const DEFAULT_PROFILE_SETTINGS: ProfileSettings = {
  nRho: 50,
  gridPacking: 4,
  rtol: 1e-2,
  atol: 1e-4,
  dtMax: 0.5,
  eqNR: 49,
  eqUpdateInterval: 10,
  transportModel: 'scaling',
  chiShape: 3,
  stiffness: 2,
  critGrad: 5,
  chiRatio: 1.0,
  DoverChi: 0.3,
  pedestalWidth: 0.06,
  etbFactor: 0.08,
  alphaCritFactor: 1,
  elmFraction: 0.35,
  pedestalModel: 'fixed',
  pedPbGradient: PB_GRADIENT,
  pedKbmCoefficient: KBM_COEFFICIENT,
  pedDensityExponent: PB_DENSITY_EXPONENT,
  elmLoss: 'fixed',
  sawtoothShear: 0.2,
  ecrhRho: 0.3,
  ecrhWidth: 0.08,
  icrhWidth: 0.3,
  nbiRtan: 0.9,
  nbcdEff: 0.25,
  eccdEff: 0.0,
  nsepFrac: 0.35,
};
