/// <reference types="node" />
/**
 * Paper figures — `npm run figures` (tsx).
 *
 * The ITER 1.5D discharge (with MHD crash snapshots and a high-cadence ELM window) runs on the main
 * thread; preset and scan discharges, the code-verification data and the POPCON grid run at the same
 * time as worker-pool tasks (src/plot/figures/tasks.worker.ts). Figures come from the registry in
 * src/plot/figures/paper.ts. Output: <out>/*.svg + *.pdf (PDF with embedded STIX Two subsets),
 * captions.md and figures.manifest.json (provenance: version, concept DOI, git SHA + dirty flag,
 * Node/V8, argv, per-figure configuration SHA-256, seeds and output SHA-256). No raw data is written.
 *   --out DIR       output folder (default docs/figures)
 *   --only a,b      only these figures; captions.md and the manifest keep the entries of the others
 *   --threads N     worker threads (default: cores − 1)
 *   --scan N        scan grid N×N (default 11)
 *   --formats f     svg,pdf (default both)
 *   --check         regenerate into a temporary folder and compare with <out>/figures.manifest.json
 *                   (exit 0 identical, 1 mismatch, 2 usage error / no manifest)
 */
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { deflateSync } from 'node:zlib';
import { nodeFontSet } from '../plot/fontsNode';
import { CaptionBlock, UnknownFigureError, captionBlock, mergeCaptions, selectFigures } from '../plot/registry';
import { FigTask, FigTaskResult, PAPER_FIGURES, PAPER_FIGURE_IDS, PaperCtx, PaperParams, RunSummary, poolTasks, runIter15 } from '../plot/figures/paper';
import { defaultThreads, runPool } from './pool';
import { defineCli, parseArgsOrExit } from './args';
import {
  CONCEPT_DOI, FigureRecord, FiguresManifest, MANIFEST_FILE, combinedConfigHash, compareWithManifest, configHash, fileRecord, gitInfo,
  mergeManifest, packageVersion, readManifest, runtimeInfo, sha256Hex, writeManifest,
} from './provenance';

const CLI = defineCli({
  name: 'npm run figures --',
  summary: 'Generates the paper figures (SVG + PDF with embedded fonts), captions.md and figures.manifest.json from the ITER 1.5D shot and pooled runs; --check verifies an existing set against its manifest.',
  flags: {
    out: { type: 'string', default: 'docs/figures', metavar: 'DIR', help: 'output folder (holds captions.md and figures.manifest.json)' },
    only: { type: 'list', choices: PAPER_FIGURE_IDS, metavar: 'FIG,…', help: 'only these figures (captions.md / manifest keep the others)' },
    threads: { type: 'int', min: 1, help: 'worker threads (default: cores − 1)' },
    scan: { type: 'int', min: 3, max: 101, help: 'scan grid size N, N×N runs (default 11)' },
    formats: { type: 'list', choices: ['svg', 'pdf'], help: 'output formats (default svg,pdf)' },
    check: { type: 'bool', help: 'regenerate into a temp folder and compare SHA-256 hashes with <out>/figures.manifest.json (exit 1 on mismatch)' },
  },
});

const DEFAULT_SCAN = 11;
const DEFAULT_FORMATS = ['svg', 'pdf'];
const deflate = (d: Uint8Array) => new Uint8Array(deflateSync(d, { level: 9 }));
const tick = () => new Promise<void>((r) => setImmediate(r));

const CAPTIONS_HEADER = `# Figure captions

Generated by \`npm run figures\` (fusion-reactor-simulator). Vector figures: SVG (web; text set in STIX Two with a Times fallback) and PDF 1.4 with embedded subsets of the STIX Two fonts (SIL Open Font License 1.1), ready for journal submission. Provenance — software version, concept DOI ${CONCEPT_DOI}, git commit, configuration SHA-256, simulation seeds and output SHA-256 — is recorded in \`figures.manifest.json\`; \`npm run figures -- --check\` regenerates the set and compares.`;

interface GenOptions { out: string; ids?: string[]; params: PaperParams; formats: string[]; threads: number }
interface GenResult { figures: Record<string, FigureRecord>; captions: CaptionBlock[]; bytes: number; nFiles: number }

async function generate(o: GenOptions): Promise<GenResult> {
  const specs = selectFigures(PAPER_FIGURES, o.ids);
  const needs = new Set(specs.flatMap((s) => s.needs));
  const fonts = nodeFontSet();
  const version = packageVersion();
  mkdirSync(o.out, { recursive: true });
  const T0 = performance.now();

  // ---- pool tasks (background)
  const tasks = poolTasks(needs, o.params);
  let nDone = 0;
  const poolP = tasks.length
    ? runPool<FigTask, FigTaskResult>(tasks, new URL('../plot/figures/tasks.worker.ts', import.meta.url), o.threads, () => { nDone++; })
    : Promise.resolve([] as FigTaskResult[]);
  console.log(`Figures → ${o.out}\n  ${tasks.length} background tasks on ${Math.min(o.threads, tasks.length)} worker threads`);

  // ---- main thread: ITER 1.5D
  const iter = needs.has('iter15') ? await runIter15({ onProgress: (p) => process.stdout.write(`  ITER15 ${p}%\r`), yieldToLoop: tick }) : null;
  if (iter) console.log(`\n  ITER15 done in ${(iter.ms / 1000).toFixed(1)} s (${iter.sim.nSteps} steps, ${iter.model.eqUpdates} GS updates); background ${nDone}/${tasks.length}`);

  const res = await poolP;
  const runs = new Map<string, RunSummary>();
  let verification: PaperCtx['verification'] = null, popcon: PaperCtx['popcon'] = null;
  for (const r of res) {
    if (!r.ok) console.log(`  WARN task ${r.id} failed: ${r.error?.split('\n')[0]}`);
    if (r.verification) verification = r.verification;
    if (r.popcon) popcon = r.popcon;
    runs.set(r.id, { id: r.id, ok: r.ok && !!r.run, error: r.error, report: r.run?.report, avg: r.run?.avg, ms: r.ms });
  }
  const ctx: PaperCtx = { params: o.params, iter, runs, verification, popcon };

  // ---- build, render, hash
  const figures: Record<string, FigureRecord> = {};
  const captions: CaptionBlock[] = [];
  let bytes = 0, nFiles = 0;
  for (const spec of specs) {
    const { fig, caption } = spec.build(ctx);
    const inputs = spec.inputs(o.params);
    const cfgHash = configHash(spec.id, inputs.config);
    const files: Record<string, { sha256: string; bytes: number }> = {};
    const emit = (name: string, data: Uint8Array | string) => {
      writeFileSync(resolve(o.out, name), data);
      files[name] = fileRecord(data);
      bytes += files[name].bytes; nFiles++;
    };
    if (o.formats.includes('svg')) emit(`${spec.file}.svg`, fig.toSVG({ fonts, deflate, version, configHash: cfgHash }));
    if (o.formats.includes('pdf')) emit(`${spec.file}.pdf`, fig.toPDF({ fonts, deflate, version, configHash: cfgHash }));
    const block = captionBlock(spec.number, spec.file, caption);
    captions.push(block);
    figures[spec.id] = {
      file: spec.file, configSha256: cfgHash, params: spec.id === 'scan' ? { scan: o.params.scan } : {}, seeds: inputs.seeds,
      files, captionSha256: sha256Hex(block.text),
    };
  }
  console.log(`  wrote ${nFiles} files (${(bytes / 1024).toFixed(0)} KiB) in ${((performance.now() - T0) / 1000).toFixed(1)} s`);
  return { figures, captions, bytes, nFiles };
}

function manifestFor(figures: Record<string, FigureRecord>, formats: string[]): FiguresManifest {
  const seeds: Record<string, number> = {};
  for (const f of Object.values(figures)) Object.assign(seeds, f.seeds);
  return {
    schema: 1, generator: 'npm run figures (src/cli/figures.cli.ts)', version: packageVersion(), conceptDoi: CONCEPT_DOI,
    git: gitInfo(), runtime: runtimeInfo(), argv: process.argv.slice(2), formats: [...formats].sort(),
    configSha256: combinedConfigHash(figures), seeds, figures,
  };
}

async function main(): Promise<number> {
  const args = parseArgsOrExit(CLI);
  const out = resolve(args.out);
  const threads = args.threads ?? defaultThreads();

  if (args.check) {
    if (args.scan !== undefined || args.formats !== undefined) {
      console.error('--check takes the scan size and formats from the manifest; do not pass --scan or --formats');
      return 2;
    }
    const manifest = readManifest(out);
    if (!manifest) { console.error(`--check: no ${MANIFEST_FILE} in ${out}`); return 2; }
    const recorded = PAPER_FIGURE_IDS.filter((id) => id in manifest.figures);
    const unknown = Object.keys(manifest.figures).filter((id) => !PAPER_FIGURE_IDS.includes(id));
    if (unknown.length) console.log(`  manifest lists figures unknown to this version: ${unknown.join(', ')}`);
    const ids = args.only ?? recorded;
    const missing = ids.filter((id) => !(id in manifest.figures));
    if (missing.length) { console.error(`--check: ${missing.join(', ')} not recorded in ${join(out, MANIFEST_FILE)}`); return 2; }
    const scan = Number(manifest.figures.scan?.params?.scan ?? DEFAULT_SCAN);
    const tmp = mkdtempSync(join(tmpdir(), 'frs-figcheck-'));
    let diff: string[];
    try {
      const gen = await generate({ out: tmp, ids, params: { scan }, formats: manifest.formats, threads });
      diff = compareWithManifest(manifest, gen.figures, ids);
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
    if (unknown.length && !args.only) diff.push(...unknown.map((id) => `${id}: in the manifest but not in the figure registry`));
    if (diff.length) {
      console.log(`\n✗ figures differ from ${join(out, MANIFEST_FILE)} (${diff.length}):\n${diff.map((d) => `  ${d}`).join('\n')}\n  (regenerate into a scratch --out folder to inspect the new files)`);
      if (manifest.runtime.node.split('.')[0] !== process.version.split('.')[0]) console.log(`  note: manifest made with Node ${manifest.runtime.node}, now ${process.version} (Math.* results may differ in the last bits)`);
      return 1;
    }
    console.log(`\n✓ ${ids.length} figure(s) identical to ${join(out, MANIFEST_FILE)}`);
    return 0;
  }

  const formats = args.formats ?? DEFAULT_FORMATS;
  const params: PaperParams = { scan: args.scan ?? DEFAULT_SCAN };
  const git = gitInfo(); // before writing: "dirty" describes the sources, not the new outputs
  const gen = await generate({ out, ids: args.only, params, formats, threads });
  const capPath = resolve(out, 'captions.md');
  writeFileSync(capPath, mergeCaptions(existsSync(capPath) ? readFileSync(capPath, 'utf8') : null, CAPTIONS_HEADER, gen.captions));
  const fresh = { ...manifestFor(gen.figures, formats), git };
  const merged = args.only ? mergeManifest(readManifest(out), fresh) : mergeManifest(null, fresh);
  writeManifest(out, merged);
  console.log(`  captions.md and ${MANIFEST_FILE} updated (${Object.keys(merged.figures).length} figures recorded)`);
  return 0;
}

main().then((code) => { process.exitCode = code; }).catch((e) => {
  if (e instanceof UnknownFigureError) { console.error(e.message); process.exitCode = 2; return; }
  console.error(e); process.exitCode = 1;
});
